### PR TITLE
Update to IBM Cloud CLI v0.6.7

### PR DESCRIPTION
**Pull request by mlocher**

### CODE REVIEW

**Comment by joesiewert** [comment]
@mlocher do you know what it would take to get this out?

**Comment by mlocher** [comment]
@joesiewert Honestly, I'm not sure. I'd update it to the latest available version of the IBM Cloud CLI, and re-run the build. There was an issue with the `dockercfg-generator`, but I didn't have time to really look into it.

**Comment by GeorgeMac** [comment]
I am merging in master to trigger a new build, since this should build successfully now I shipped a fix in jet to support the auth strategy needed to build this.

**Comment by joesiewert** [comment]
Awesome, looks good @GeorgeMac! 🎉

**Review by joesiewert — APPROVED** [review]

**Pull request merged**
